services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
    networks:
      - net
    volumes:
      - ./src:/opt/src_data/
      - ./sql_init_scripts/ddl_postgres.sql:/docker-entrypoint-initdb.d/ddl_postgres.sql

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
    environment:
      CLICKHOUSE_PASSWORD: 123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    networks:
      - net
    volumes:
      - ./sql_init_scripts/ddl_clickhouse.sql:/docker-entrypoint-initdb.d/ddl_clickhouse.sql

  apache-spark:
    container_name: spark
    image: spark:python3
    command: /opt/spark/sbin/start-master.sh && tail -f /dev/null
    ports:
      - "8080:8080"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_WEBUI_PORT: 8080
      SPARK_NO_DAEMONIZE: true 
    depends_on:
      - postgres
      - clickhouse
      - mongo
      - mongo-express
    networks:
      - net
    volumes:
      - ./scripts:/opt/etl/scripts/
      - ./jars:/opt/etl/drivers/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    networks:
      - net

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:123@mongo:27017/"
      ME_CONFIG_BASICAUTH_ENABLED: false
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - net
  
networks:
  net:
    driver:
      bridge
